### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by MisinformedDNA** [DevTeam/Pure.DI#11]
I've been learning about this project and I'm excited to try it out. I think it has great potential. Unfortunately, the name is pretty bad. It's not imaginative nor is it searchable and discovery is key. Even removing the dot and using `PureDI` makes it more searchable.

Some other alternatives might be:

- PurDI (maybe pronounced purr-dee or pure-dee)
- DIGen
- InjectGen
- Injectinator

Keep up the good work!

**Comment by NikolayPianikov** [comment]
Thank you. It is good idea. Now the difficulty is only in finding this project or does the name sound really bad? What does Google search find for the search query "Pure DI"? I'm asking because there is difficulty - some customers already uses the NuGet package with id _Pure.DI_ and I don't want to inconvenience them. Renaming the project itself to GitHub is not difficult. We can temporarily release packages with 2 IDs, new and old one _Pure.DI_.

**Comment by MisinformedDNA** [comment]
Your search results have increased greatly in the last 10 days. :) And I'm not a fan of the name, but that isn't enough reason to break things. The only other issue is that `DI` is both a namespace and a type. 

At this point, I would say, don't rename the project, but maybe rename the namespace to just `PureDI`.
