### ISSUE TITLE
Simple example not working -what I have done wrong? 

### ISSUE THREAD

**Issue by ignatandrei** [DevTeam/Pure.DI#78]
I maintain a list of Roslyn Code Generators at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

However , your Pure.DI is causing me problems to understand the function .

I have an interface IDatabase, an DatabaseCon that implements IDatabase ( without constructor) and a Database that implements IDatabase and has a constructor like 
```csharp 
public Database(IDatabase con)
```
(Think decorator for IDatabase)

I was thinking to this implementation
```csharp
using InjectDemo;
using Pure.DI;
DI.Setup("Composition")
    .Bind<IDatabase>().To<DatabaseCon>()
    .Bind<Database>().To<Database>()
    ;

var c = new Composition();
var con = c.Resolve<IDatabase>();
con.Open();
```

But it gives me " Cannot resolve composition root of type InjectDemo.Database " .
Please tell me what's wrong.
 I have attached the project to can reproduce.

[src.zip](https://github.com/user-attachments/files/18222920/src.zip)

**Comment by NikolayPianikov** [comment]
@ignatandrei Pure.DI is a code generator, it generates code before the compilation process. It needs to know in advance what types will be the roots of the compositions you will be working with. Otherwise it would have to create code for all possible variants, which is very expensive and not reasonable.

So based on your example you need a composition root of type `Database`:

```c#
using InjectDemo;
using Pure.DI;

DI.Setup("Composition")
    .Bind<IDatabase>().To<DatabaseCon>()
    .Bind<Database>().To<Database>()
    // You must specify the composition root(s)
    .Root<Database>("Database")
    ;

var c = new Composition();
var con = c.Resolve<Database>();
con.Open();
```

Since the number of roots is limited, properties or methods are created for all the roots of the composition to get them. It is recommended not to use the _ServiceLocator_ approach to obtain roots using the method `Resolve<Database>()`. Therefore, it is better to rewrite the code like this:

```c#
using InjectDemo;
using Pure.DI;

DI.Setup("Composition")
    .Bind<IDatabase>().To<DatabaseCon>()
    .Bind<Database>().To<Database>()
    // You must specify the composition root(s)
    .Root<Database>("Database")
    ;

var c = new Composition();
var con = c.Database;
con.Open();
```

Moreover, in this case you will never get the exception you saw in your example, because the code for your composition root will be like this:

```c#
partial class Composition
{
  public Database Database
  {
    get
    {
      return new Database(new DatabaseCon());
    }
  }
}
```

Bindings like `Bind<Database>().To<Database>()` are only needed if you want to use an abstract type in the dependencies, `Database` is not abstract (it doesn't require "mapping") and can be created, so no binding is needed for it:

```c#
using InjectDemo;
using Pure.DI;

DI.Setup("Composition")
    .Bind<IDatabase>().To<DatabaseCon>()
    .Root<Database>("Database")
    ;

var c = new Composition();
var con = c.Database;

con.Open();
```

**Comment by NikolayPianikov** [comment]
@ignatandrei, please see these examples:
- [Auto-bindings](https://github.com/DevTeam/Pure.DI/blob/master/readme/auto-bindings.md)
- [Injections of abstractions](https://github.com/DevTeam/Pure.DI/blob/master/readme/injections-of-abstractions.md)

**Comment by ignatandrei** [comment]
Thank you. I have added at 

https://ignatandrei.github.io/RSCG_Examples/v2/docs/Pure.DI
