### ISSUE TITLE
Unclear error DI007 when compilation errors were occurred

### ISSUE THREAD

**Issue by kant2002** [DevTeam/Pure.DI#8]
Shroedinger cat sample. Create separate classlib and move 3 classes to there `State`, `ICat` and `ShroedingersCat`
following error
```
error DI007: Sample.ShroedingersCat is not inherited from Sample.ICat
```
If I move `ShroedingersCat` back to console app, everything working again.

**Comment by NikolayPianikov** [comment]
@kant2002 please make sure that types in ClassLibrary have appropriate keywords (public) to make them accessible for other assembly and there are no any other compilation errors. I've created a sample:
[ShroedingersCat.zip](https://github.com/DevTeam/Pure.DI/files/8889683/ShroedingersCat.zip)

**Comment by kant2002** [comment]
Ahh. That maybe the case. Still that strange error to see. Let me check

**Comment by kant2002** [comment]
Indeed you was right! That was strange enough error that I miss that obvious solution. Thanks

**Comment by NikolayPianikov** [comment]
Pure.DI checked that ShroedingersCat does not implement ICat because of compilation errors and raised this unclear error. But it has got an information that this tree was not compiled correctly and I perhaps should fix the messages text for this case or just skip raising this error for this specific case. Thx for reporting this bug
